version: '3'

services:
  auth-server: # go based authentication server
    build:
      context: ./AuthServer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - appnet
  web-server: # Flask based webserver
    build:
      context: ./WebServer
      dockerfile: Dockerfile
    links:
      - "auth-server:auth-server"
    ports:
      - "5000:5000"
    networks:
      - appnet

networks:
  appnet:
